version: "3"
services:
  postgres:
    image: postgres:latest
    volumes:
      - postgres-data:/var/lib/postgresql/data
    expose:
      - 5432
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=admin
      - POSTGRES_USER=postgres
      - POSTGRES_DB=testdb
    restart: unless-stopped
  twelve-factor-app:
    image: twelve-factor:latest
    expose:
      - 8080
    environment:
      - spring.datasource.username=admin1
      - spring.datasource.password=postgres1
    restart: unless-stopped
    depends_on:
      - postgres
    links:
      - postgres
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - twelve-factor-app
    ports:
      - "4000:4000"
volumes:
  postgres-data:
